name: stream_video_push_notification
description: Adds push notification support for Stream Video, a service for
  building video calls, audio rooms, and live-streaming applications.
version: 0.6.0
homepage: https://getstream.io/video/
repository: https://github.com/GetStream/stream-video-flutter
issue_tracker: https://github.com/GetStream/stream-video-flutter/issues

publish_to: none # This makes the package private and unpublishable

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.17.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_callkit_incoming:
    git:
      url: https://github.com/francisnatty/flutter_callkit_incoming.git
      ref: master
  flutter_webrtc: ^0.11.7
  #flutter_callkit_incoming: ^2.0.4+1
  json_annotation: ^4.9.0
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0
  stream_video: ^0.5.5
  uuid: ^4.2.1
  shared_preferences: ^2.3.2
